<a href="https://colab.research.google.com/github/Amma-Anjali/Generative_AI_2025/blob/main/gen_ai_2303A52385_week1_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
y_actual_reg = np.array([20, 30, 40, 50, 60])
y_pred_reg = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

In [3]:
mae_manual = np.mean(np.abs(y_actual_reg - y_pred_reg))
mse_manual = np.mean((y_actual_reg - y_pred_reg)**2)
rmse_manual = np.sqrt((mse_manual))
r2_manual = 1 - (np.sum((y_actual_reg - y_pred_reg)**2) / np.sum((y_actual_reg - np.mean(y_actual_reg))**2))

In [4]:
print("Regression Metrics")
print(f"MAE: Manual = {mae_manual}")
print(f"MSE: Manual = {mse_manual}")
print(f"RMSE: Manual = {rmse_manual}")
print(f"R2 Score: Manual = {r2_manual}")

Regression Metrics
MAE: Manual = 0.4600000000000016
MSE: Manual = 0.24600000000000147
RMSE: Manual = 0.49598387070549127
R2 Score: Manual = 0.99877


In [5]:
mae_lib = mean_absolute_error(y_actual_reg, y_pred_reg)
mse_lib = mean_squared_error(y_actual_reg, y_pred_reg)
rmse_lib = np.sqrt(mse_lib)
r2_lib = r2_score(y_actual_reg, y_pred_reg)

In [6]:
print("Regression Metrics")
print(f"MAE: Sklearn = {mae_lib}")
print(f"MSE: Sklearn = {mse_lib}")
print(f"RMSE: Sklearn = {rmse_lib}")
print(f"R2 Score: Sklearn = {r2_lib}")

Regression Metrics
MAE: Sklearn = 0.4600000000000016
MSE: Sklearn = 0.24600000000000147
RMSE: Sklearn = 0.49598387070549127
R2 Score: Sklearn = 0.99877


In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [8]:
y_actual_cls = np.array([0, 0, 0, 0, 0,
                         1, 1, 1, 1, 1,
                         2, 2, 2, 2, 2])

y_pred_cls = np.array([0, 0, 1, 2, 0,
                        0, 1, 0, 2, 0,
                        1, 2, 2, 1, 2])

In [9]:
accuracy = accuracy_score(y_actual_cls, y_pred_cls)
precision = precision_score(y_actual_cls, y_pred_cls, average = "macro")
recall = recall_score(y_actual_cls, y_pred_cls, average = "macro")
f1 = f1_score(y_actual_cls, y_pred_cls, average = "macro")
conf_matrix = confusion_matrix(y_actual_cls, y_pred_cls)

In [10]:
print("\nClassification Metrics")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)


Classification Metrics
Accuracy : 0.4667
Precision: 0.4500
Recall: 0.4667
F1-Score: 0.4559
Confusion Matrix:
[[3 1 1]
 [3 1 1]
 [0 2 3]]


In [11]:
print("\nClassification Report:")
print(classification_report(y_actual_cls, y_pred_cls))


Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       0.25      0.20      0.22         5
           2       0.60      0.60      0.60         5

    accuracy                           0.47        15
   macro avg       0.45      0.47      0.46        15
weighted avg       0.45      0.47      0.46        15

